routes/web.php
<?php

use App\Http\Controllers\ApartmentController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PropertyController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class,'index'])->name('home');

Route::get('properties', [ApartmentController::class,'index'])->name('properties');
Route::get('properties/{slug}', [ApartmentController::class,'detail'])->name('property.detail');
Route::get('city/{slug}', [ApartmentController::class,'city'])->name('property.city');
Route::get('search', [ApartmentController::class,'search'])->name('apartment.search');
Route::get('news', [MediaController::class,'news'])->name('news');
Route::get('categories/{slug}', [MediaController::class,'category'])->name('news.category');
Route::get('tags/{slug}', [MediaController::class,'tag'])->name('news.tag');
Route::get('news/{slug}', [MediaController::class,'detail'])->name('news.detail');
Route::post('comment', [MediaController::class,'comment'])->name('news.comment');
Route::get('search/news', [MediaController::class,'search'])->name('news.search');
Route::get('contact', [MediaController::class,'contact'])->name('contact');
Route::post('contact', [MediaController::class,'store'])->name('contact.store');
Route::post('message/apartment', [ApartmentController::class,'message']);
Route::get('page-not-found', function () {
    return view('errors.404');
})->name('errors');

Route::prefix('user')->group(function () {
    Route::get('dashboard',[HomeController::class,'dashboard'])->name('user.dashboard');
    Route::get('property',[HomeController::class,'property'])->name('user.property');
    Route::post('property',[HomeController::class,'store'])->name('user.store');
    Route::get('profile',[HomeController::class,'profile'])->name('user.profile');
    Route::put('profile/update',[HomeController::class,'update'])->name('user.update');
    Route::get('changepwd',[HomeController::class,'changepwd'])->name('user.changepwd');
    Route::put('change',[HomeController::class,'change'])->name('user.change');
    Route::delete('destroy/{id}',[HomeController::class,'destroy'])->name('user.destroy');
});

Auth::routes();

Route::middleware(['authadmin', 'auth'])->group(function () {
    Route::get('dashboard',[DashboardController::class,'index'])->name('dashboard');
    Route::resource('property',PropertyController::class);
    Route::resource('category',CategoryController::class)->except(['show']);
    Route::resource('tag',TagController::class)->except(['show']);
    Route::resource('post',PostController::class);
    Route::get('setting',[DashboardController::class,'setting'])->name('setting');
    Route::put('setting',[DashboardController::class,'store'])->name('setting.store');
    Route::get('admin/profile',[DashboardController::class,'adminProfile'])->name('admin.profile');
    Route::put('admin/profile',[DashboardController::class,'profile'])->name('admin.profile.store');
    Route::get('admin/password',[DashboardController::class,'password'])->name('admin.password');
    Route::put('admin/update-pwd',[DashboardController::class,'update'])->name('admin.password.update');
    Route::get('admin/message',[DashboardController::class,'message'])->name('admin.message');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Post extends Model
{
    use HasFactory;

    protected $table = "posts";

    /**
     * Get the category that owns the Post
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    /**
     * Get the tag that owns the Post
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function tag(): BelongsTo
    {
        return $this->belongsTo(Tag::class, 'tag_ud');
    }

    /**
     * Get the user that owns the Post
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Get all of the comment_post for the Post
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comment_post(): HasMany
    {
        return $this->hasMany(CommentPost::class);
    }

    /**
     * Get all of the post_tag for the Post
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function post_tag(): HasMany
    {
        return $this->hasMany(PostTag::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use App\Models\PostTag;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::paginate(5);

        return view('backend.post.index',compact('posts'));
    }

    public function removeImage($file){
        $path = public_path('upload/post/'.$file->image);
        if(isset($path))
            unlink($path);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('backend.post.create',compact('categories','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'image' => 'required|image|mimes:jpeg,jpg,png,svg,gif|max:2048',
            'quote' => 'required',
            'category' => 'required',
            'tags' => 'required'
        ],[

        ]);

        $post = new Post();
        $post->name = $request->name;
        $post->slug = Str::slug($request->name).'-'.Carbon::now()->timestamp;
        $post->short_description = $request->short_description;
        $post->description = $request->description;
        $post->quote = $request->quote;
        $post->category_id = $request->category;
        $post->user_id = Auth::user()->id;

        if ($request->hasFile('image')) {
            $imageName = $post->slug.'.'.$request->image->extension();
            $request->image->storeAs('post',$imageName);
            $post->image = $imageName;
        }
        $post->save();

        foreach ($request->tags as $tag) {
            $post_tag = new PostTag();
            $post_tag->post_id = $post->id;
            $post_tag->tag_id = $tag;
            $post_tag->save();
        }

        session()->flash('message','Thêm bài viết thành công !');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);

        return view('backend.post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        $categories = Category::where('id','!=',$post->category_id)->get();        
        $post_tags = PostTag::where('post_id',$post->id)->get();
        $tags = Tag::all();

        return view('backend.post.update',compact('post','categories','tags','post_tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'new_image' => 'image|mimes:jpeg,jpg,png,svg,gif|max:2048',
            'quote' => 'required',
            'category' => 'required',
        ],[

        ]);

        $post = Post::find($id);
        $post->name = $request->name;
        $post->slug = Str::slug($request->name).'-'.Carbon::now()->timestamp;
        $post->short_description = $request->short_description;
        $post->description = $request->description;
        $post->quote = $request->quote;
        $post->category_id = $request->category;
        $post->user_id = Auth::user()->id;

        if ($request->hasFile('new_image')) {
            $this->removeImage($post);
            $imageName = $post->slug.'.'.$request->new_image->extension();
            $request->new_image->storeAs('post',$imageName);
            $post->image = $imageName;
        }
        $post->save();
        if ($request->new_tags) {
            $tags = PostTag::where('post_id',$post->id)->get();
            foreach ($tags as $tag) {
                $tag->delete();
            }
            foreach ($request->new_tags as $tag) {
                $post_tag = new PostTag();
                $post_tag->post_id = $post->id;
                $post_tag->tag_id = $tag;
                $post_tag->save();
            }
        }

        session()->flash('message','Cập nhật bài viết thành công !');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $this->removeImage($post);
        $post->delete();

        session()->flash('message','Xóa bài viết thành công !');
        return back();
    }
}

resources/views/backend/post/create.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>Thêm bài viết
            </h2>
        </div>
    </div>
</div>
<div class="container-fluid">
    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12">
            @if (Session::has('message'))
            <div class="alert alert-success">{{ Session::get('message') }}</div>
            @endif
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Thêm mới bài viết</strong></h2>
                    <a href="{{ route('post.index') }}" class="btn btn-primary float-right">Quay lại</a>
                </div>
                <div class="body">
                    <form id="form_validation" action="{{ route('post.store') }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="form-group form-float">
                            <input type="text" class="form-control" placeholder="Tiêu đề" name="name" required>
                            @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group form-float">
                            <textarea type="text" class="form-control" id="short_description" placeholder="Mô tả ngắn"
                                name="short_description" rows="15"></textarea>
                        </div>
                        <div class="form-group form-float">
                            <textarea type="text" class="form-control" id="description" placeholder="Mô tả chi tiết"
                                name="description" rows="25"></textarea>
                            @error('description')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group form-float">
                            <input type="text" class="form-control" placeholder="Trích dẫn" name="quote" required>
                            @error('quote')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group form-float">
                            <select class="form-control show-tick ms search-select" name="category">
                                <option value="">Chọn danh mục</option>
                                @foreach ($categories as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                            @error('category')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <fieldset>
                            <p>Chọn chủ đề</p>
                            @foreach ($tags as $item)
                            <div>
                                <input type="checkbox" name="tags[]" value="{{ $item->id }}">
                                <label for="tags">{{ $item->name }}</label>
                            </div>
                            @endforeach
                            @error('tags')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </fieldset>
                        <div class="form-group form-float">
                            <label for="image">Hình ảnh</label>
                            <input type="file" class="form-control" name="image" required>
                            @error('image')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <button class="btn btn-raised btn-primary btn-round waves-effect" type="submit">Lưu</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Validation -->
</div>
@endsection
@push('scripts')
<script src="https://cdn.tiny.cloud/1/wl0hy3kumawhadevkqc4e81r6m900s5jbcbx30qu575s6ptk/tinymce/5/tinymce.min.js"
referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#short_description'
    })
    tinymce.init({
        selector: '#description'
    })
</script>
@endpush

resources/views/backend/post/index.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>Danh sách danh mục
            </h2>
        </div>
    </div>
</div>
<div class="container-fluid">
    <!-- Basic Table -->
    <div class="row clearfix">
        <div class="col-lg-12">
            @if (Session::has('message'))
                <div class="alert alert-success">{{ Session::get('message') }}</div>
            @endif
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Danh sách</strong></h2>
                    <a href="{{ route('post.create') }}" class="btn btn-primary float-right">Thêm mới</a>
                </div>
                <div class="body table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Hình ảnh</th>
                                <th>Tiêu đề</th>
                                <th>Đường dẫn</th>
                                <th><i class="material-icons">remove_red_eye</i></th>
                                <th> <i class="material-icons">comments</i></th>
                                <th>Cập nhật</th>
                                <th>Xóa</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($posts as $key => $post)
                            <tr id="property{{ $post->id }}">
                                <th scope="row">{{ ++$key }}</th>
                                <td>
                                    <img src="{{ asset('upload/post') }}/{{ $post->image }}" width="150" alt="{{ $post->name }}">
                                </td>
                                <td>{{ $post->name }}</td>
                                <td>{{ $post->slug }}</td>
                                <td>{{ $post->view }}</td>
                                <td>
                                    @if ($post->comment_post)
                                        {{ $post->comment_post->count() }}
                                    @else
                                        0
                                    @endif
                                </td>
                                <td> 
                                    <a href="{{ route('post.edit',['post' => $post->id]) }}" class="text-success">
                                        <i class="material-icons">mode_edit</i>
                                    </a> 
                                </td>
                                <td>
                                    <form id="delete-form" action="{{ route('post.destroy',['post' => $post->id]) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-link" type="submit"><span class="text-danger"><i class="material-icons">delete</i></span></button>
                                    </form>
                                </td>
                            </tr>                                                        
                            @endforeach
                        </tbody>
                    </table>
                    {{ $posts->links() }}
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
</div>
@endsection

resources/views/backend/post/update.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>Cập nhật bài viết
            </h2>
        </div>
    </div>
</div>
<div class="container-fluid">
    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12">
            @if (Session::has('message'))
            <div class="alert alert-success">{{ Session::get('message') }}</div>
            @endif
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Cập nhật bài viết</strong></h2>
                    <a href="{{ route('post.index') }}" class="btn btn-primary float-right">Quay lại</a>
                </div>
                <div class="body">
                    <form id="form_validation" action="{{ route('post.update',['post' => $post->id]) }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="form-group form-float">
                            <input type="text" class="form-control" placeholder="Tiêu đề" value="{{ $post->name }}" name="name" required>
                            @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group form-float">
                            <textarea type="text" class="form-control" id="short_description" placeholder="Mô tả ngắn"
                                name="short_description" rows="15">{{ $post->short_description }}</textarea>
                        </div>
                        <div class="form-group form-float">
                            <textarea type="text" class="form-control" name="description" placeholder="Mô tả chi tiết"
                                name="description" rows="25">{{ $post->description }}</textarea>
                            @error('description')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group form-float">
                            <input type="text" class="form-control" placeholder="Trích dẫn" value="{{ $post->quote }}" name="quote" required>
                            @error('quote')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group form-float">
                            <select class="form-control show-tick ms search-select" name="category">
                                <option value="{{ $post->category_id }}">{{ $post->category->name }}</option>
                                @foreach ($categories as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <fieldset>
                            <span>Chủ đề đã chọn: </span>
                            @foreach ($post_tags as $tag)                                   
                                <span class="font-italic">{{ $tag->tag->name }},    </span>
                            @endforeach
                            <p>Chủ đề</p>
                            @foreach ($tags as $tag)                                   
                                <div>
                                    <input type="checkbox" name="new_tags[]" value="{{ $tag->id }}">
                                    <label for="tags">{{ $tag->name }}</label>
                                </div>
                            @endforeach
                            @error('tags')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </fieldset>
                        <div class="form-group form-float">
                            <label for="image">Hình ảnh</label>
                            <input type="file" class="form-control" name="new_image">
                            <img src="{{ asset('upload/post') }}/{{ $post->image }}" width="150" alt="{{ $post->name }}">
                            @error('image')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <button class="btn btn-raised btn-primary btn-round waves-effect" type="submit">Lưu</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Validation -->
</div>
@endsection
@push('scripts')
<script src="https://cdn.tiny.cloud/1/wl0hy3kumawhadevkqc4e81r6m900s5jbcbx30qu575s6ptk/tinymce/5/tinymce.min.js"
referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#short_description'
    })
    tinymce.init({
        selector: '#description'
    })
</script>
@endpush