routes/web.php
<?php

use App\Http\Controllers\ApartmentController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PropertyController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class,'index'])->name('home');

Route::get('properties', [ApartmentController::class,'index'])->name('properties');
Route::get('properties/{slug}', [ApartmentController::class,'detail'])->name('property.detail');
Route::get('city/{slug}', [ApartmentController::class,'city'])->name('property.city');
Route::get('search', [ApartmentController::class,'search'])->name('apartment.search');
Route::get('news', [MediaController::class,'news'])->name('news');
Route::get('categories/{slug}', [MediaController::class,'category'])->name('news.category');
Route::get('tags/{slug}', [MediaController::class,'tag'])->name('news.tag');
Route::get('news/{slug}', [MediaController::class,'detail'])->name('news.detail');
Route::post('comment', [MediaController::class,'comment'])->name('news.comment');
Route::get('search/news', [MediaController::class,'search'])->name('news.search');
Route::get('contact', [MediaController::class,'contact'])->name('contact');
Route::post('contact', [MediaController::class,'store'])->name('contact.store');
Route::post('message/apartment', [ApartmentController::class,'message']);
Route::get('page-not-found', function () {
    return view('errors.404');
})->name('errors');

Route::prefix('user')->group(function () {
    Route::get('dashboard',[HomeController::class,'dashboard'])->name('user.dashboard');
    Route::get('property',[HomeController::class,'property'])->name('user.property');
    Route::post('property',[HomeController::class,'store'])->name('user.store');
    Route::get('profile',[HomeController::class,'profile'])->name('user.profile');
    Route::put('profile/update',[HomeController::class,'update'])->name('user.update');
    Route::get('changepwd',[HomeController::class,'changepwd'])->name('user.changepwd');
    Route::put('change',[HomeController::class,'change'])->name('user.change');
    Route::delete('destroy/{id}',[HomeController::class,'destroy'])->name('user.destroy');
});

Auth::routes();

Route::middleware(['authadmin', 'auth'])->group(function () {
    Route::get('dashboard',[DashboardController::class,'index'])->name('dashboard');
    Route::resource('property',PropertyController::class);
    Route::resource('category',CategoryController::class)->except(['show']);
    Route::resource('tag',TagController::class)->except(['show']);
    Route::resource('post',PostController::class);
    Route::get('setting',[DashboardController::class,'setting'])->name('setting');
    Route::put('setting',[DashboardController::class,'store'])->name('setting.store');
    Route::get('admin/profile',[DashboardController::class,'adminProfile'])->name('admin.profile');
    Route::put('admin/profile',[DashboardController::class,'profile'])->name('admin.profile.store');
    Route::get('admin/password',[DashboardController::class,'password'])->name('admin.password');
    Route::put('admin/update-pwd',[DashboardController::class,'update'])->name('admin.password.update');
    Route::get('admin/message',[DashboardController::class,'message'])->name('admin.message');
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Tag extends Model
{
    use HasFactory;

    protected $table = "tags";

    /**
     * Get all of the post for the Tag
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function post(): HasMany
    {
        return $this->hasMany(Post::class);
    }

    /**
     * Get all of the post_tag for the Tag
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function post_tag(): HasMany
    {
        return $this->hasMany(PostTag::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::paginate(10);

        return view('backend.tag.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ],[
            'name.required' => 'Tên chủ đề không được trống !'
        ]);

        $tag = new Tag();
        $tag->name = $request->name;
        $tag->slug = Str::slug($request->name).'-'.Carbon::now()->timestamp;
        $tag->save();

        session()->flash('message','Thêm chủ đề thành công !');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);

        return view('backend.tag.update',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
        ],[
            'name.required' => 'Tên chủ đề không được trống !'
        ]);

        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->slug = Str::slug($request->name).'-'.Carbon::now()->timestamp;
        $tag->save();

        session()->flash('message','Cập nhật chủ đề thành công !');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::find($id)->delete();
        session()->flash('message','Xóa chủ đề thành công !');
        return back();
    }
}

resources/views/backend/tag/create.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>Thêm chủ đề
            </h2>            
        </div>
    </div>
</div>
<div class="container-fluid">
    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12">
            @if (Session::has('message'))
                <div class="alert alert-success">{{ Session::get('message') }}</div>
            @endif
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Thêm mới chủ đề</strong></h2>
                    <a href="{{ route('tag.index') }}" class="btn btn-primary float-right">Quay lại</a>
                </div>
                <div class="body">
                    <form id="form_validation" action="{{ route('tag.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group form-float">
                            <input type="text" class="form-control" placeholder="Tên chủ đề" name="name" required>
                            @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>                        
                        <button class="btn btn-raised btn-primary btn-round waves-effect" type="submit">Lưu</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Validation -->
</div>
@endsection

resources/views/backend/tag/index.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>Danh sách chủ đề
            </h2>
        </div>
    </div>
</div>
<div class="container-fluid">
    <!-- Basic Table -->
    <div class="row clearfix">
        <div class="col-lg-12">
            @if (Session::has('message'))
                <div class="alert alert-success">{{ Session::get('message') }}</div>
            @endif
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Danh sách</strong></h2>
                    <a href="{{ route('tag.create') }}" class="btn btn-primary float-right">Thêm mới</a>
                </div>
                <div class="body table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Tên chủ đề</th>
                                <th>Đường dẫn</th>
                                <th>Cập nhật</th>
                                <th>Xóa</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($tags as $key => $tag)
                            <tr id="property{{ $tag->id }}">
                                <th scope="row">{{ ++$key }}</th>
                                <td>{{ $tag->name }}</td>
                                <td>{{ $tag->slug }}</td>
                                <td> 
                                    <a href="{{ route('tag.edit',['tag' => $tag->id]) }}" class="text-success">
                                        <i class="material-icons">mode_edit</i>
                                    </a> 
                                </td>
                                <td>
                                    <form id="delete-form" action="{{ route('tag.destroy',['tag' => $tag->id]) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-link" type="submit"><span class="text-danger"><i class="material-icons">delete</i></span></button>
                                    </form>
                                </td>
                            </tr>                                                        
                            @endforeach
                        </tbody>
                    </table>
                    {{ $tags->links() }}
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
</div>
@endsection

resources/views/backend/tag/update.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>Cập nhật chủ đề
            </h2>            
        </div>
    </div>
</div>
<div class="container-fluid">
    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12">
            @if (Session::has('message'))
                <div class="alert alert-success">{{ Session::get('message') }}</div>
            @endif
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Cập nhật chủ đề</strong></h2>
                    <a href="{{ route('tag.index') }}" class="btn btn-primary float-right">Quay lại</a>
                </div>
                <div class="body">
                    <form id="form_validation" action="{{ route('tag.update',['tag' => $tag->id]) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="form-group form-float">
                            <input type="text" class="form-control" placeholder="Tên chủ đề" name="name" value="{{ $tag->name }}" required>
                            @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>                        
                        <button class="btn btn-raised btn-primary btn-round waves-effect" type="submit">Cập nhật</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Validation -->
</div>
@endsection 